### ISSUE TITLE
ipyparallel

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyter#201]
a small remark; doing `pip install jupyter' on a somewat empty python-2.7.12, I get a warning when launching jupyter_notebook (that works, beside the warning):

````
[W 18:46:00.700 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 18:46:00.744 NotebookApp] Writing notebook server cookie secret to C:\WinPython\basedir27\buildZero\winpython-64bit-2.7.x.3\scripts\..\settings\runtime\notebook_cookie_secret
[W 18:46:00.839 NotebookApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "C:\WinPython\basedir27\buildZero\winpython-64bit-2.7.x.3\python-2.7.12.amd64\lib\site-packages\notebook\notebookapp.py", line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\WinPython\basedir27\buildZero\winpython-64bit-2.7.x.3\python-2.7.12.amd64\lib\importlib\__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named ipyparallel.nbextension
````

maybe the procedure `pip install jupyter` is not enough ?

**Comment by stonebig** [comment]
pip list:
`````

backports-abc (0.4)
backports.shutil-get-terminal-size (1.0.0)
certifi (2016.8.31)
colorama (0.3.7)
configparser (3.5.0)
decorator (4.0.10)
docopt (0.6.2)
entrypoints (0.2.2)
functools32 (3.2.3.post2)
idlex (1.13)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.1.1)
MarkupSafe (0.23)
mistune (0.7.3)
nbconvert (4.2.0)
nbformat (4.1.0)
notebook (4.2.2)
pathlib2 (2.1.0)
pickleshare (0.7.4)
pip (8.1.2)
prompt-toolkit (1.0.7)
ptpython (0.35)
Pygments (2.1.3)
pythonnet (2.1.0)
pyzmq (15.4.0)
qtconsole (4.2.1)
setuptools (25.1.6)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
sqlite-bro (0.8.11)
tornado (4.4.1)
traitlets (4.2.2)
wcwidth (0.1.7)
widgetsnbextension (1.2.6)
win-unicode-console (0.5)
winpython (1.6.20160816)
````

**Comment by minrk** [comment]
The error is because `ipyparallel` is enabled in your configuration (see `jupyter serverextension list`), but not installed. The `jupyter` metapackage doesn't depend on ipyparallel (not sure if this is intentional or not), but you can install it after the fact if you want it.

**Comment by stonebig** [comment]
hum, ok. that's a bug of me so, but I prefer to let it as this is complex machinery to add it after.

thanks for the inquiry.

**Comment by stonebig** [comment]
so you mean  the metapackage doesn't include ipyparallel ?

**Comment by shanmugavel28** [comment]
if you are using conda -  try `conda install ipyparallel`  It worked for me

**Comment by MotorCityCobra** [comment]
pip install ipyparallel --upgrade
