### ISSUE TITLE
it takes jupyter-notebook more than 30 seconds to start

### ISSUE THREAD

**Issue by LuciusCao** [jupyter/jupyter#211]
Hi,

I'm running Jupyter Notebook on Mac OS 10.12 with Python 3.5.2. It used to work well and respond rapidly after I enter Jupyter Notebook. But, I occasionally reinstalled python 3.5.2 with the downloaded .dmg from Python official site. After that, when I run jupyter-notebook it takes the system more than 30 seconds to actually start the browser and to show some stdout in terminal.

Could you help to investigate why it takes so long to start the notebook and how to fix this problem?

Thanks a lot

**Comment by takluyver** [comment]
That much of a slowdown can be a DNS issue. @minrk?

Try hitting Ctrl-C while it starts up, and see where it's getting stuck from the traceback.

**Comment by LuciusCao** [comment]
Here's the traceback
^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'ip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/notebook/notebookapp.py", line 1071, in initialize
    self.init_webapp()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/notebook/notebookapp.py", line 912, in init_webapp
    self.login_handler_class.validate_security(self, ssl_options=ssl_options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/notebook/auth/login.py", line 89, in validate_security
    if not app.ip:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/notebook/notebookapp.py", line 447, in _ip_default
    s.bind(('localhost', 0))
KeyboardInterrupt

And yes it is a DNS issue. I removed the hosts file and now it is as responding as it was. Thanks a lot! This issue is solved.

**Comment by minrk** [comment]
Yup, 30 seconds is a magic number for DNS issues.
