### ISSUE TITLE
IPython Console crashs when browsing history with magic-command

### ISSUE THREAD

**Issue by scriptmode** [jupyter/jupyter#235]
Version:
- IPython 5.1.0
- Python 2.7.6

Setting:
- Open kernel (ipython kernel)
- Connect with a console to kernel (ipython console --existing kernel-12345.json)
- Go through the history and reach an entry with % (%connect_info for example)

Result:
Console crashs instantly with this Traceback:

``` python
In [1]: Traceback (most recent call last):
  File "/home/user/.local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/user/.local/lib/python2.7/site-packages/jupyter_console/app.py", line 155, in start
    self.shell.mainloop()
  File "/home/user/.local/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 490, in mainloop
    self.interact()
  File "/home/user/.local/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 474, in interact
    code = self.prompt_for_code()
  File "/home/user/.local/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 430, in prompt_for_code
    reset_current_buffer=True)
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 425, in run
    self._redraw()
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/renderer.py", line 429, in render
    extended_height=size.rows,
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 1000, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/controls.py", line 502, in preferred_height
    content = self.create_content(cli, width, None)
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/layout/controls.py", line 616, in create_content
    document = buffer.document
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 451, in document
    self.text, self.cursor_position, self.selection_state]
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/cache.py", line 90, in __missing__
    result = self.get_value(*key)
  File "/home/user/.local/lib/python2.7/site-packages/prompt_toolkit/document.py", line 83, in __init__
    assert isinstance(text, six.text_type), 'Got %r' % text
AssertionError: Got '%connect_info'
```

**Comment by takluyver** [comment]
Can you file this on the [jupyter_console repo](https://github.com/jupyter/jupyter_console)? Thanks.
