### ISSUE TITLE
Jupyter kernel unknown error

### ISSUE THREAD

**Issue by duytrung** [jupyter/jupyter#279]
G'day,

I run jupyter notebook and it showed me this error:

```
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Anaconda\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Anaconda\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Anaconda\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Anaconda\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "C:\Anaconda\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 94, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Anaconda\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "C:\Anaconda\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Is this error due to the failed installation/upgrade of python from 3.6.1. to 3.6.2?

I upgrade the python via conda recently.

Here is my list of packages installed:

```
> conda list
# packages in environment at C:\Anaconda:
#
_license                  1.1                      py36_1
alabaster                 0.7.10                   py36_0    conda-forge
anaconda                  custom                   py36_0
anaconda-client           1.6.3                    py36_0    conda-forge
anaconda-navigator        1.6.3                    py36_0
anaconda-project          0.6.0                    py36_0
asn1crypto                0.22.0                   py36_0    conda-forge
astroid                   1.4.8                    py36_0    conda-forge
astropy                   2.0.1               np113py36_1    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
automat                   0.6.0                    py36_0    conda-forge
babel                     2.3.4                    py36_0    conda-forge
backports                 1.0                      py36_0
beautifulsoup4            4.5.3                    py36_0    conda-forge
bitarray                  0.8.1                    py36_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blaze                     0.10.1                   py36_0
bleach                    1.5.0                    py36_0    conda-forge
bokeh                     0.12.6                   py36_0    conda-forge
boto                      2.48.0                   py36_0
bottleneck                1.2.0               np113py36_0    conda-forge
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.2                    py36_1    conda-forge
chest                     0.2.3                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
cloudpickle               0.3.1                    py36_0    conda-forge
clyent                    1.2.1                    py36_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
comtypes                  1.1.2                    py36_0
conda                     4.3.23                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py36_0
console_shortcut          0.1.1                    py36_1
constantly                15.1.0                   py36_0
contextlib2               0.5.5                    py36_0    conda-forge
cryptography              1.9                      py36_0    conda-forge
cssselect                 1.0.1                    py36_0
curl                      7.49.1                   vc14_2  [vc14]  conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.26                     py36_0    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
dask                      0.15.1                   py36_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
dill                      0.2.6                    py36_0    conda-forge
distributed               1.18.0                   py36_0    conda-forge
django                    1.11.4                   py36_0    conda-forge
docutils                  0.13.1                   py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
flask                     0.12                     py36_0    conda-forge
flask-cors                3.0.3                    py36_0    conda-forge
freetype                  2.7                      vc14_1  [vc14]  conda-forge
get_terminal_size         1.0.0                    py36_0
gevent                    1.2.2                    py36_0    conda-forge
greenlet                  0.4.12                   py36_0    conda-forge
h5py                      2.7.0               np113py36_1    conda-forge
hdf5                      1.8.18                   vc14_0  [vc14]  conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
hyperlink                 17.1.1                   py36_0
hypothesis                3.17.0                   py36_0    conda-forge
icu                       58.1                     vc14_1  [vc14]  conda-forge
idna                      2.5                      py36_0    conda-forge
imageio                   2.2.0                    py36_0    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
incremental               16.10.1                  py36_0
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                6.0.0                    py36_0    conda-forge
isort                     4.2.5                    py36_0    conda-forge
itsdangerous              0.24                     py36_1    conda-forge
jdcal                     1.3                      py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.5                    py36_0    conda-forge
joblib                    0.11                     py36_0    conda-forge
jpeg                      9b                       vc14_0  [vc14]  conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
lazy-object-proxy         1.3.0                    py36_0    conda-forge
libgpuarray               0.6.9                    vc14_0  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.28                   vc14_0  [vc14]  conda-forge
libpython                 2.0                      py36_0
libtiff                   4.0.6                    vc14_7  [vc14]  conda-forge
libxml2                   2.9.4                    vc14_4  [vc14]  conda-forge
libxslt                   1.1.29                   vc14_5  [vc14]  conda-forge
llvmlite                  0.19.0                   py36_0
locket                    0.2.0                    py36_1    conda-forge
lxml                      3.8.0                    py36_0    conda-forge
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
mako                      1.0.7                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
menuinst                  1.4.7                    py36_0
mistune                   0.7.4                    py36_0    conda-forge
mkl                       2017.0.3                      0
mkl-service               1.1.2                    py36_3
mpmath                    0.19                     py36_2    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9                    py36_0    conda-forge
navigator-updater         0.1.0                    py36_0
nbconvert                 5.2.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
networkx                  1.11                     py36_0    conda-forge
nltk                      3.2.4                    py36_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numba                     0.34.0              np113py36_5
numexpr                   2.6.2               np113py36_0    conda-forge
numpy                     1.13.1                   py36_0
numpydoc                  0.7.0                    py36_0    conda-forge
odo                       0.5.1                    py36_0    conda-forge
olefile                   0.44                     py36_0    conda-forge
openpyxl                  2.5.0a2                  py36_0    conda-forge
openssl                   1.0.2l                   vc14_0  [vc14]  conda-forge
packaging                 16.8                     py36_0    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
parsel                    1.2.0                    py36_0
partd                     0.3.8                    py36_0    conda-forge
path.py                   10.3.1                   py36_0
pathlib2                  2.3.0                    py36_0    conda-forge
patsy                     0.4.1                    py36_0    conda-forge
pep8                      1.7.0                    py36_0
pickleshare               0.7.3                    py36_0    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.2.1                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
py4j                      0.10.6                   py36_1    conda-forge
pyasn1                    0.3.2                    py36_0    conda-forge
pyasn1-modules            0.0.9                    py36_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycosat                   0.6.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycurl                    7.43.0                   py36_1
pydispatcher              2.0.5                    py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygame                    1.9.3                     <pip>
pygments                  2.2.0                    py36_0    conda-forge
pygpu                     0.6.9               np113py36_0    conda-forge
pylearn2                  0.6.stable.201601.18.g517dc87          py36_0
pylint                    1.6.5                    py36_0    conda-forge
pymc3                     3.1                      py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pyodbc                    4.0.17                   py36_0    conda-forge
pyopenssl                 16.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyreadline                2.1                      py36_0
pysocks                   1.6.7                    py36_0    conda-forge
pyspark                   2.2.0                    py36_0    conda-forge
pytables                  3.4.2               np113py36_1    conda-forge
pytest                    3.2.0                    py36_0    conda-forge
python                    3.6.2                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pywavelets                0.5.2               np113py36_0    conda-forge
pywin32                   220                      py36_1    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.0                    py36_0    conda-forge
qtpy                      1.2.1                    py36_0    conda-forge
queuelib                  1.4.2                    py36_0
requests                  2.18.3                   py36_0    conda-forge
rope                      0.10.5                   py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
scikit-image              0.13.0                   py36_1    conda-forge
scikit-learn              0.18.2              np113py36_0
scipy                     0.19.1              np113py36_0
scrapy                    1.4.0                    py36_0    conda-forge
seaborn                   0.8.0                    py36_0    conda-forge
service_identity          17.0.0                   py36_0
setuptools                36.2.2                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sockjs-tornado            1.0.3                    py36_0
sortedcollections         0.4.2                    py36_0    conda-forge
sortedcontainers          1.5.3                    py36_0    conda-forge
sphinx                    1.6.3                    py36_0    conda-forge
sphinxcontrib             1.0                      py36_0
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.0                    py36_0    conda-forge
sqlalchemy                1.1.11                   py36_0    conda-forge
statsmodels               0.8.0               np113py36_0    conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
testpath                  0.3                      py36_0    conda-forge
theano                    0.9.0                    py36_1    conda-forge
tk                        8.6.6                    vc14_5  [vc14]  conda-forge
toolz                     0.8.2                    py36_0    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
tqdm                      4.15.0                   py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
twisted                   17.5.0                   py36_0
typing                    3.6.1                    py36_0    conda-forge
unicodecsv                0.14.1                   py36_0    conda-forge
urllib3                   1.21.1                   py36_1    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
w3lib                     1.17.0                   py36_0
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.12.2                   py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0    conda-forge
win_inet_pton             1.0.1                    py36_1    conda-forge
win_unicode_console       0.5                      py36_0
wincertstore              0.2                      py36_0    conda-forge
wrapt                     1.10.8                   py36_0    conda-forge
xlrd                      1.0.0                    py36_1    conda-forge
xlsxwriter                0.9.6                    py36_0    conda-forge
xlwings                   0.11.4                   py36_0    conda-forge
xlwt                      1.2.0                    py36_0    conda-forge
yaml                      0.1.6                    vc14_0  [vc14]  conda-forge
zict                      0.1.2                    py36_0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge
zope                      1.0                      py36_0
zope.interface            4.4.2                    py36_0
```

Thank you!

**Comment by Carreau** [comment]
try reinstalling the kernelspec : `python -m ipykernel install`. It's strange that upgrading the conda from 3.6.1 to 3.6.2 does that, but it may have change the Python path.

**Comment by ivanov** [comment]
G'day, I'm going through old issues and it seems to me that it makes sense to close this one. Hopefully you got your issue resolved.

Thanks everyone and happy hacking! :bowtie:
