### ISSUE TITLE
Swagger API with Bravado?

### ISSUE THREAD

**Issue by mikepurvis** [jupyter/jupyter#297]
This code:

```
from bravado.client import SwaggerClient
client = SwaggerClient.from_url('http://localhost:8888/api/spec.yaml')
```

Results in this:

```
Traceback (most recent call last):
  File "notebook-api-test.py", line 7, in <module>
    client = SwaggerClient.from_url('http://localhost:8888/api/spec.yaml')
  File "/usr/local/lib/python2.7/site-packages/bravado/client.py", line 113, in from_url
    spec_dict = loader.load_spec(spec_url)
  File "/usr/local/lib/python2.7/site-packages/bravado/swagger_model.py", line 103, in load_spec
    return self.load_yaml(response.text)
  File "/usr/local/lib/python2.7/site-packages/bravado/swagger_model.py", line 117, in load_yaml
    data = yaml.safe_load(text)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python2.7/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 29, column 18:
              urlArgs: "v=20171103164722",
```

Is there a recommended way to talk to the Notebook API from Python? Alternatively, if Swagger support is experimental, is there a recommended client for the [Contents API](https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API#notebook-and-file-contents-api)? Based on that documentation, I can just roll my own, but I'd love not to, if there's an officially supported/endorsed option that I'm just missing.

**Comment by rgbkrk** [comment]
They continue to get updates (as recently as of #2943), so if there's an issue with the spec.yaml we would love your contributions.

**Comment by mikepurvis** [comment]
I'm not really an expert with Swagger or REST APIs in general— I'm just trying to programmatically create and populate notebooks from Python, and finding it surprisingly tough to get going. Can you recommend any examples which would be good to work from?

**Comment by Carreau** [comment]
If you are "just" creating notebook I would consider using nbfomat
directly:

https://github.com/jupyter/nbformat

There is no need to have a running server to create a notebook.

Notebook are json file that respect a schema, you could almost create  them
by hand.
-- 
Matthias

**Comment by mikepurvis** [comment]
I'm hoping to do this on a remote instance, where I don't necessarily have access to the filesystem, but that can be worked around, I suppose.

The larger issue is that I had problems in the past with copying/pasting a notebook in that the old and new versions would continue to "share" the same Python kernel on the backend, leading to chaos as the two notebook contents diverged but they had chunks of each other's state showing up in the cells. When I saw that behaviour, it seemed safest to do everything from within prescribed Jupyter APIs rather than manipulating the filesystem behind its back.

**Comment by Carreau** [comment]
> The larger issue is that I had problems in the past with copying/pasting a notebook in that the old and new versions would continue to "share" the same Python kernel on the backend, leading to chaos as the two notebook contents diverged but they had chunks of each other's state showing up in the cells. When I saw that behaviour, it seemed safest to do everything from within prescribed Jupyter APIs rather than manipulating the filesystem behind its back.

That is weird; the file itself does not keep a handle on which kernel instance it is connected to.
So copying from the filesystem should be relative safe. We may have a bug somewhere if that is not the case.

**Comment by mikepurvis** [comment]
Huh, okay— that's helpful to know. I had the issue with a much older version (ipython 3.1.0), so it's possible it's something was fixed along the way, or there were other shenanigans at work, but knowing that that _shouldn't_ happen is good.

**Comment by mikepurvis** [comment]
Getting back to the main thrust of this ticket, it's just weird to me that Bravado error looks to be some kind of yaml validation problem, and it's happening fairly early on in the process. Whereas if I parse the yaml myself and just pass in an in-memory spec rather than a URL, eg:

```
from bravado.client import SwaggerClient
import yaml

with open('api.yaml') as f:
    spec = yaml.load(f)
client = SwaggerClient.from_spec(spec)
```

Then it's some other weird validation issue:

```
Traceback (most recent call last):
  File "notebook-api-test.py", line 7, in <module>
    client = SwaggerClient.from_spec(spec)
  File "/usr/local/lib/python2.7/site-packages/bravado/client.py", line 145, in from_spec
    spec_dict, origin_url, http_client, config)
  File "/usr/local/lib/python2.7/site-packages/bravado_core/spec.py", line 205, in from_dict
    spec.build()
  File "/usr/local/lib/python2.7/site-packages/bravado_core/spec.py", line 217, in build
    self._validate_spec()
  File "/usr/local/lib/python2.7/site-packages/bravado_core/spec.py", line 213, in _validate_spec
    http_handlers=build_http_handlers(self.http_client),
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 81, in validate_spec
    http_handlers=http_handlers,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 22, in wrapper
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 129, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
    schema_path=property,
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 216, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 16, in patternProperties
    v, subschema, path=k, schema_path=pattern,
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 216, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
    schema_path=property,
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 216, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
    schema_path=property,
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 216, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 121, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 105, in iter_errors
    for error in errors:
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 117, in validator_wrapper
    default_validator_callable,
  File "/usr/local/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 159, in deref_and_validate
    validator, schema_element, instance, schema):
  File "/usr/local/lib/python2.7/site-packages/jsonschema/_validators.py", line 14, in patternProperties
    if re.search(pattern, k):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
swagger_spec_validator.common.SwaggerValidationError: expected string or buffer
``` 

Pasting a JSON-ified version of the spec into [this validator](http://bigstickcarpet.com/swagger-parser/www/index.html) says it's okay, so maybe the issue here is with Bravado rather than the swagger spec from Jupyter.

----

Okay, yeah sure enough, using `swagger-codegen` seems to accept this file just fine:

```
swagger-codegen generate -i spec.yaml -l python -o jupyter-python
```

So this is a problem elsewhere.
