### ISSUE TITLE
Jupyter Kernel error (Urgent)

### ISSUE THREAD

**Issue by karthivenkatesh** [jupyter/jupyter#328]
Dear All,

I have installed apache toree for my spark application using the command.

pip install https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0/snapshots/dev1/toree-pip/toree-0.2.0.dev1.tar.gz
jupyter toree install

My conda & python version
------------------
conda --version
conda 4.4.11
python --version
Python 3.6.4 :: Anaconda custom (64-bit)

$ jupyter kernelspec list
---------------------------
Available kernels:
  apache_toree_pyspark    C:\Users\venk\AppData\Roaming\jupyter\kernels\apache_toree_pyspark
  apache_toree_scala      C:\Users\venk\AppData\Roaming\jupyter\kernels\apache_toree_scala
  apache_toree_sparkr     C:\Users\venk\AppData\Roaming\jupyter\kernels\apache_toree_sparkr
  apache_toree_sql        C:\Users\venk\AppData\Roaming\jupyter\kernels\apache_toree_sql

jupyter toree install --interpreters=Scala --spark_home=C:/Spark --user --kernel_name=apache_toree --interpreters=PySpark,SparkR,Scala,SQL

**All all the above-listed kernels are in the dead state.**

While launching jupyter notebook --no-browser getting below errors
=================================================

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1512, in _execute
    result = yield result
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by kangzhang0709** [comment]
hi,did you solve this problem? I also meet this issure.

**Comment by karthivenkatesh** [comment]
Issue not solved yet. Can any one help me to resolve

**Comment by rafalfirlejczyk** [comment]
I tried the to install on Windows the Apache Scala kernel using Toree as well. I did not succeed either. 
However I managed to connect the Spark with jupyter network by defining two new Environment System Variables. (Go to _System Properties/Advanced/Environment Variables/System variables_ and add new variables)
Variable name=**PYSPARK_DRIVER_PYTHON**
Variable value=**jupyter**
and 
Variable name=**PYSPARK_DRIVER_PYTHON_OPTS
Variable value=**notebook**

**Note: **NO quotes** for jupyter and notebook.**

Then, when you run your pyspark from the directory where you have your jupyter notebook files, it will open the jupyter notebook for you. 
For example when my jupyter notebook files are located in the directory:
**C:\Users\rafal\**
and my pyspark is located in:
**C:\spark\bin\**
I have to run:
_C:\Users\rafal>_**C:\spark\bin\pyspark**

You can also confirm that the spark it is working by running:
http://localhost:4040/jobs/

**Comment by unuseid** [comment]
It might be to late already, but If you still need solve this problem.
I found answer, so here it is

add ' shell = True ' at
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189

return launch_kernel(kernel_cmd, **kw)        
to
return launch_kernel(kernel_cmd, **kw, shell=True)

seems like bad porting problem for Python windows,
and they decide to won't fix it

I was reference this 
https://bugs.python.org/issue26493 
https://bugs.python.org/issue17023

**Comment by amiradinari** [comment]
@unuseid I took ur recommendation ,but i did not work !! 
any other recommendations!!

**Comment by amiradinari** [comment]
the answer is here :
https://issues.apache.org/jira/browse/TOREE-406

**Comment by EveDong** [comment]
> the answer is here :
> https://issues.apache.org/jira/browse/TOREE-406

I did not find the answer. Could you please show me your solution? Thanks!

**Comment by hackerphysics** [comment]
> It might be to late already, but If you still need solve this problem.
> 
> ### I found answer, so here it is
> add ' shell = True ' at
> File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189
> 
> `return launch_kernel(kernel_cmd, **kw) `
> to
> `return launch_kernel(kernel_cmd, **kw, shell=True)`
> 
> seems like bad porting problem for Python windows,
> and they decide to won't fix it
> 
> I was reference this
> https://bugs.python.org/issue26493
> https://bugs.python.org/issue17023
> 
> After I solved this problem,
> I faced with Kernel Time out
> 
> `[W 16:40:03.312 NotebookApp] Timeout waiting for kernel_info reply from bb2254df-22f3-4ef2-a3cb-dfb1223aa357`
> 
> If someone after me face this problem and solve this, please teach me

It works for me!

**Comment by EveDong** [comment]
> > It might be to late already, but If you still need solve this problem.
> > ### I found answer, so here it is
> > add ' shell = True ' at
> > File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189
> > `return launch_kernel(kernel_cmd, **kw) `
> > to
> > `return launch_kernel(kernel_cmd, **kw, shell=True)`
> > seems like bad porting problem for Python windows,
> > and they decide to won't fix it
> > I was reference this
> > https://bugs.python.org/issue26493
> > https://bugs.python.org/issue17023
> > After I solved this problem,
> > I faced with Kernel Time out
> > `[W 16:40:03.312 NotebookApp] Timeout waiting for kernel_info reply from bb2254df-22f3-4ef2-a3cb-dfb1223aa357`
> > If someone after me face this problem and solve this, please teach me
> 
> It works for me!

Did you face with kernel time out after modifying "manager.py"?

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
