### ISSUE TITLE
Unable to launch Jupyter notebook from anaconda

### ISSUE THREAD

**Issue by Sharique121** [jupyter/jupyter#349]
Hi I am trying to launch Jupyternotebook from Anaconda Navigator but I am getting the following error

Traceback (most recent call last):
File "C:\Users\Sharique Ahmed\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\Sharique Ahmed\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in 
from .nbextensions import install_nbextension
File "C:\Users\Sharique Ahmed\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in 
from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

Please help!

**Comment by Sharique121** [comment]
My issue got resolved

i had to install the following package

conda update jupyter_core jupyter_client
