### ISSUE TITLE
Having "Kernel error" in jupyter notebook

### ISSUE THREAD

**Issue by weichang252** [jupyter/jupyter#356]
The error message shows as below. I am running jupyter notebook in one of my environments. How do I solve it? Many thanks.

Traceback (most recent call last):
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\traitlets\traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\notebook\base\handlers.py", line 540, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 123, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
    self.start_restarter()
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\jupyter_client\ioloop\manager.py", line 49, in start_restarter
    kernel_manager=self, loop=self.loop,
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\traitlets\traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\traitlets\traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\traitlets\traitlets.py", line 589, in _validate
    value = self.validate(obj, value)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\traitlets\traitlets.py", line 1675, in validate
    self.error(obj, value)
  File "C:\Users\wdy\AppData\Local\conda\conda\envs\my_root\lib\site-packages\traitlets\traitlets.py", line 1522, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000000005EA89B0>) was specified.

**Comment by weichang252** [comment]
If having the same issue, refer to #3397

`pip3  install tornado==4.5.3` solve the issue.
