### ISSUE TITLE
Jupyter with python 3.7

### ISSUE THREAD

**Issue by AlexisPrel** [jupyter/jupyter#357]
Hi,

Since I have updated python to its latest version (3.7) jupyter notebooks fail to launch. This does not affect IPython which works just fine. It seems to be related to a change in the webbrowser module. I don't know if you are aware of this and of any (temporary) solution other than reverting to an older version of python ?

Jupyter:
```
[username@my_computer ~]$ jupyter-notebook 
[I 14:26:34.188 NotebookApp] Serving notebooks from local directory: /home/username
[I 14:26:34.188 NotebookApp] 0 active kernels
[I 14:26:34.188 NotebookApp] The Jupyter Notebook is running at:
[I 14:26:34.188 NotebookApp] http://localhost:8888/?token=081479bf6dff5e22a453e3c3c4ca2d09dacd2b405794c6c5
[I 14:26:34.188 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 11, in <module>
    load_entry_point('notebook==5.3.0', 'console_scripts', 'jupyter-notebook')()
  File "/usr/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.7/site-packages/notebook/notebookapp.py", line 1597, in start
    browser = webbrowser.get(self.browser or None)
  File "/usr/lib/python3.7/webbrowser.py", line 42, in get
    register_standard_browsers()
  File "/usr/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given

```

IPython:
```
[username@my_computer ~]$ ipython
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
```

**Comment by takluyver** [comment]
We are aware (https://github.com/jupyter/notebook/issues/3837 , https://github.com/jupyter/notebook/issues/3840 ). You may be able to work around it by unsetting the BROWSER environment variable.

See https://bugs.python.org/issue31014 for more detail.

**Comment by AlexisPrel** [comment]
Thank you!

**Comment by shahramsaghaei** [comment]
Where is the webbrowser.py file? how to find it?

**Comment by SRITANU** [comment]
> Where is the webbrowser.py file? how to find it?
In `anaconda3/lib/python3.7/webbrowser.py`
