### ISSUE TITLE
Error running Jupyter after recent update

### ISSUE THREAD

**Issue by juliohm** [jupyter/jupyter#360]
After a system update today (Antergos Linux), I am getting the following error message when trying to start Jupyter notebooks:

```
$ jupyter notebook
[W 21:32:32.804 NotebookApp] Collisions detected in /home/juliohm/.jupyter/jupyter_notebook_config.py and /home/juliohm/.jupyter/jupyter_notebook_config.json config files. /home/juliohm/.jupyter/jupyter_notebook_config.json has higher priority: {
      "NotebookApp": {
        "nbserver_extensions": "{'jlstaticserve': True} ignored, using {'jupyterlab': True}"
      }
    }
[I 21:32:32.987 NotebookApp] JupyterLab extension loaded from /home/juliohm/.local/lib/python3.7/site-packages/jupyterlab
[I 21:32:32.987 NotebookApp] JupyterLab application directory is /home/juliohm/.local/share/jupyter/lab
[I 21:32:32.993 NotebookApp] Serving notebooks from local directory: /home/juliohm
[I 21:32:32.993 NotebookApp] 0 active kernels
[I 21:32:32.993 NotebookApp] The Jupyter Notebook is running at:
[I 21:32:32.993 NotebookApp] http://localhost:8888/?token=eda6ed399cbe9a1851ef3eacbc476b221f9d9680979848ce
[I 21:32:32.993 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 11, in <module>
    load_entry_point('notebook==5.3.0', 'console_scripts', 'jupyter-notebook')()
  File "/usr/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.7/site-packages/notebook/notebookapp.py", line 1597, in start
    browser = webbrowser.get(self.browser or None)
  File "/usr/lib/python3.7/webbrowser.py", line 42, in get
    register_standard_browsers()
  File "/usr/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

So apparently, the notebook starts successfully, but then the web browser fails to start?

Appreciate any help.

**Comment by juliohm** [comment]
The issue is more serious, and a fix is described here: https://github.com/jupyter/notebook/issues/3837

**Comment by Nicholas-Mitchell** [comment]
Perhaps a mindless hack (I'm not 100% sure of the inner-workings), but simple making the fourth argument a *named* argument worked for me.

Given the error message, we are looking at line 116 of `webbrowser.py`. There I changed this:

`register(browser, None, controller, update_tryorder)
`

to this:

`register(browser, None, controller, preferred=update_tryorder)
`

Now running `jupyter notebook` works as expected!

---

The fix suggested around the environment variable `BROWSER` ([here](https://github.com/jupyter/notebook/issues/3840)) didn't do anything for me.
