### ISSUE TITLE
Issue when am using jupyter on Anaconda / actually anything on anaconda

### ISSUE THREAD

**Issue by CrystializeD** [jupyter/jupyter#364]
I just installed anaconda latest version and nothing is working but i don't care about mos of the stuff, i just want jupyter but it's giving me this error, i'd really appreciate the help. 
am running windows 7 x 64

Error Text : 

[W 21:12:35.089 NotebookApp] Cannot bind to localhost, using 127.0.0.1 as default ip
[Errno 11004] getaddrinfo failed
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 10, in 
sys.exit(main())
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
app.initialize(argv)
File "", line 2, in initialize
File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1602, in initialize
self.init_webapp()
File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1381, in init_webapp
self.http_server.listen(port, self.ip)
File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 144, in listen
sockets = bind_sockets(port, address=address)
File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\netutil.py", line 163, in bind_sockets
sock.bind(sockaddr)
OSError: [WinError 10049] The requested address is not valid in its context

**Comment by 1kastner** [comment]
Have you installed a debugger and stepped through the program to see what the value of `sockaddr` is? E.g. PyCharm offers a quite nice debugging experience.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
