### ISSUE TITLE
unable to run jupyter notebook in fedora

### ISSUE THREAD

**Issue by kirankotari** [jupyter/jupyter#403]
I am using `fedora 4.13.16-100.fc25.x86_64`. 

My python version `3.5.6` I have install jupyter but unable to start it.

`
$jupyter notebook
` 

__Getting the following error__
```
xyz ~/Desktop/jup $ jupyter notebook 
Traceback (most recent call last):
  File "/home/xyz/.pyenv/versions/3.5.6/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 10, in <module>
    import sqlite3
  File "/home/xyz/.pyenv/versions/3.5.6/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/xyz/.pyenv/versions/3.5.6/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyz/.pyenv/versions/3.5.6/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/home/xyz/.pyenv/versions/3.5.6/lib/python3.5/site-packages/notebook/notebookapp.py", line 86, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/home/xyz/.pyenv/versions/3.5.6/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ImportError: No module named 'pysqlite2'
```

**Comment by ZhaoFeiK** [comment]
+1

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
