### ISSUE TITLE
Kernel keyerror error trying Jupyter

### ISSUE THREAD

**Issue by Arthur-Milchior** [jupyter/jupyter#414]
Hi.
I'm on ubuntu. I've got pip.
I did
sudo -H pip3 install jupyter
and then
jupyter notebook

I then try to create a new notebook. And it shows a «kernel error» with message

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.6/dist-packages/notebook/services/sessions/handlers.py", line 67, in post
    model = yield gen.maybe_future(sm.get_session(path=path))
  File "/usr/local/lib/python3.6/dist-packages/notebook/services/sessions/sessionmanager.py", line 170, in get_session
    return self.row_to_model(row)
  File "/usr/local/lib/python3.6/dist-packages/notebook/services/sessions/sessionmanager.py", line 209, in row_to_model
    raise KeyError
KeyError

**Comment by nelsonauner** [comment]
+1

**Comment by choldgraf** [comment]
you could try restarting your terminal to see if it's a paths problem.

The issues in this repository aren't checked often, the place to ask general questions about jupyter etc is at discourse.jupyter.org, you'll probably have better luck finding help there!

**Comment by Arthur-Milchior** [comment]
Thank you for letting me know. I'll also suggest to remove «bug report» on github then, and have them clearly indicates this website instead.

And no, restarting the terminal/computer does not helps.

**Comment by choldgraf** [comment]
Hmm - could you clarify what you mean by "remove <<bug report>>"? The issue template for this repository should be directing people to open issues in discourse.jupyter.org. It should say this:

```
Welcome to the jupyter meta repository! 👋🏻

This repository is the home of the Jupyter-wide documentation. However,
it **not** the best place to ask questions about Jupyter.

If you have a question or an issue about one of the tools in Jupyter,
we recommend asking in the Jupyter community Discourse forum at the
link below:

https://discourse.jupyter.org

Thanks!
```

do you not see that when you create a new issue? If not we should debug that...

**Comment by Erhao** [comment]
I had the same problem when opening a .ipynb file, but when I opening other .ipynb files everything was fine, all the .ipynb files are very common py scripts. 
the "Kernel error":
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/sessions/handlers.py", line 67, in post
    model = yield gen.maybe_future(sm.get_session(path=path))
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/sessions/sessionmanager.py", line 170, in get_session
    return self.row_to_model(row)
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/sessions/sessionmanager.py", line 209, in row_to_model
    raise KeyError
KeyError
```
![image](https://user-images.githubusercontent.com/35090558/209772608-3363ea49-65ff-4533-b23b-fd55b59f55c4.png)

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Anyone who runs into this should search for similar issues on https://github.com/jupyter/notebook/ or open a new one there.

Thanks everyone and happy hacking! :bowtie:
