### ISSUE TITLE
OSError: libiconv.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bencaine1** [jupyter/jupyter#431]
We started getting this error some time yesterday afternoon when trying to run `conda install jupyter`. Full stack trace:
```
Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/opt/conda/lib/python2.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/opt/conda/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/opt/conda/lib/python2.7/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/opt/conda/lib/python2.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/opt/conda/lib/python2.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/opt/conda/lib/python2.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/opt/conda/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/opt/conda/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory
```
If we run `conda install libiconv` before running `conda install jupyter`, then it works fine.

Might be a similar issue to https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1153.

**Comment by ivanov** [comment]
closing this, it looks like this was a temporary packaging issue, at least according to resolution of https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1153
