### ISSUE TITLE
Install Error Jupyter (pandocfilters>=1.4.1)

### ISSUE THREAD

**Issue by Dm-Af** [jupyter/jupyter#507]
Hello, dear developers!
I try to install Jupyter to my Orange Pi PC Plus!
But installation can't be complete because when installing module pandocfilters 1.4.1, installation terminating and I watch next error:
`user@PC:~$ sudo pip3 install jupyter`

`WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.`

`WARNING: The directory '/home/user/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

`Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)`

`Collecting jupyter-console
  Downloading jupyter_console-6.1.0-py2.py3-none-any.whl (21 kB)`

`Collecting nbconvert
  Downloading nbconvert-5.6.1-py2.py3-none-any.whl (455 kB)
     |████████████████████████████████| 455 kB 525 kB/s`

`Collecting ipywidgets
  Downloading ipywidgets-7.5.1-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 399 kB/s`

`Collecting notebook
  Downloading notebook-6.0.3-py3-none-any.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 693 kB/s`

`Collecting qtconsole
  Downloading qtconsole-4.7.4-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 619 kB/s`

`Collecting ipykernel
  Downloading ipykernel-5.2.1-py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 553 kB/s`

`Requirement already satisfied: ipython in /usr/lib/python3/dist-packages (from jupyter-console->jupyter) (2.4.1)`

`Collecting pygments
  Downloading Pygments-2.6.1-py3-none-any.whl (914 kB)
     |████████████████████████████████| 914 kB 534 kB/s`

`Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-2.0.10-py3-none-any.whl (340 kB)
     |████████████████████████████████| 340 kB 714 kB/s`

`Collecting jupyter-client
  Downloading jupyter_client-6.1.3-py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 583 kB/s`

`Collecting entrypoints>=0.2.2
  Downloading entrypoints-0.3-py2.py3-none-any.whl (11 kB)`

`Collecting bleach
  Downloading bleach-3.1.5-py2.py3-none-any.whl (151 kB)
     |████████████████████████████████| 151 kB 651 kB/s`

`Collecting nbformat>=4.4
  Downloading nbformat-5.0.6-py3-none-any.whl (170 kB)
     |████████████████████████████████| 170 kB 664 kB/s`

`Collecting traitlets>=4.2
  Downloading traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 808 kB/s`

`Requirement already satisfied: jinja2>=2.4 in /usr/lib/python3/dist-packages (from nbconvert->jupyter) (2.8)`

`Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)`

`Collecting defusedxml
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)`

`Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.4.2.tar.gz (14 kB)`

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4_ja8hh2/pandocfilters/setup.py'"'"'; __file__='"'"'/tmp/pip-i                      nstall-4_ja8hh2/pandocfilters/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp                      ile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1v6bwsj7
         cwd: /tmp/pip-install-4_ja8hh2/pandocfilters/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    ----------------------------------------
`
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Maybe it can to help:

```

user@PC:~$ pip3 --version
pip 20.1 from /home/user/.local/lib/python3.5/site-packages/pip (python 3.5)
user@PC:~$ pip --version
pip 20.1 from /home/user/.local/lib/python3.5/site-packages/pip (python 3.5)
user@PC:~$ python --version
Python 2.7.12
user@PC:~$ python3 --version
Python 3.5.2
user@PC:~$ uname -a
Linux PC 3.4.113-sun8i #2 SMP PREEMPT Wed May 8 15:09:43 CEST 2019 armv7l armv7l armv7l GNU/Linux
user@PC:~$

user@PC:~$ dpkg -l ipython*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-=======================================================================================
ii  ipython                                   2.4.1-1                   all                       enhanced interactive Python shell
un  ipython-doc                               <none>                    <none>                    (no description available)
ii  ipython-notebook                          2.4.1-1                   all                       interactive Python html notebook
ii  ipython-notebook-common                   2.4.1-1                   all                       interactive Python html notebook data package
un  ipython-qtconsole                         <none>                    <none>                    (no description available)
ii  ipython3                                  2.4.1-1                   all                       enhanced interactive Python 3 shell
ii  ipython3-notebook                         2.4.1-1                   all                       interactive Python 3 html notebook
un  ipython3-qtconsole                        <none>                    <none>                    (no description available)

user@PC:~$ dpkg -l python*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-=======================================================================================
ii  python                                    2.7.12-1~16.04            armhf                     interactive high-level object-oriented language (default version)
un  python-4suite                             <none>                    <none>                    (no description available)
un  python-acoustid                           <none>                    <none>                    (no description available)
un  python-all                                <none>                    <none>                    (no description available)
un  python-all-dbg                            <none>                    <none>                    (no description available)
un  python-all-dev                            <none>                    <none>                    (no description available)
un  python-apt                                <none>                    <none>                    (no description available)
ii  python-apt-common                         1.1.0~beta1ubuntu0.16.04. all                       Python interface to libapt-pkg (locales)
un  python-apt-doc                            <none>                    <none>                    (no description available)
un  python-aptdaemon-gtk                      <none>                    <none>                    (no description available)
un  python-argparse                           <none>                    <none>                    (no description available)
ii  python-bittorrent                         3.4.2-12                  all                       Scatter-gather network file transfer
un  python-boto                               <none>                    <none>                    (no description available)
ii  python-cairo                              1.8.8-2                   armhf                     Python bindings for the Cairo vector graphics library
un  python-central                            <none>                    <none>                    (no description available)
un  python-chardet-whl                        <none>                    <none>                    (no description available)
un  python-colorama-whl                       <none>                    <none>                    (no description available)
ii  python-crypto                             2.6.1-6ubuntu0.16.04.3    armhf                     cryptographic algorithms and protocols for Python
un  python-crypto-dbg                         <none>                    <none>                    (no description available)
un  python-crypto-doc                         <none>                    <none>                    (no description available)
un  python-ctypes                             <none>                    <none>                    (no description available)
un  python-cupshelpers                        <none>                    <none>                    (no description available)
un  python-dbg                                <none>                    <none>                    (no description available)
un  python-dbus-doc                           <none>                    <none>                    (no description available)
ii  python-decorator                          4.0.6-1                   all                       simplify usage of Python decorators by programmers
un  python-dev                                <none>                    <none>                    (no description available)
un  python-distlib-whl                        <none>                    <none>                    (no description available)
ii  python-dnspython                          1.12.0-1                  all                       DNS toolkit for Python
un  python-doc                                <none>                    <none>                    (no description available)
un  python-email                              <none>                    <none>                    (no description available)
un  python-examples                           <none>                    <none>                    (no description available)
un  python-gi                                 <none>                    <none>                    (no description available)
un  python-gobject                            <none>                    <none>                    (no description available)
ii  python-gobject-2                          2.28.6-12ubuntu1          armhf                     deprecated static Python bindings for the GObject library
un  python-gobject-2-dbg                      <none>                    <none>                    (no description available)
ii  python-gtk2                               2.24.0-4ubuntu1           armhf                     Python bindings for the GTK+ widget set
un  python-gtk2-doc                           <none>                    <none>                    (no description available)
un  python-gtkglext1                          <none>                    <none>                    (no description available)
un  python-healpy                             <none>                    <none>                    (no description available)
un  python-html5lib-whl                       <none>                    <none>                    (no description available)
ii  python-imaging                            3.1.2-0ubuntu1.3          all                       Python Imaging Library compatibility layer
un  python-imaging-compat                     <none>                    <none>                    (no description available)
un  python-importlib                          <none>                    <none>                    (no description available)
ii  python-jinja2                             2.8-1ubuntu0.1            all                       small but fast and easy to use stand-alone template engine
un  python-jinja2-doc                         <none>                    <none>                    (no description available)
ii  python-ldb                                2:1.1.24-1ubuntu3.1       armhf                     Python bindings for LDB
un  python-lxml-doc                           <none>                    <none>                    (no description available)
ii  python-markupsafe                         0.23-2build2              armhf                     HTML/XHTML/XML string library for Python
un  python-matplotlib                         <none>                    <none>                    (no description available)
ii  python-matplotlib-data                    1.5.1-1ubuntu1            all                       Python based plotting system (data package)
un  python-matplotlib-doc                     <none>                    <none>                    (no description available)
ii  python-minimal                            2.7.12-1~16.04            armhf                     minimal subset of the Python language (default version)
un  python-numpy                              <none>                    <none>                    (no description available)
un  python-numpy-doc                          <none>                    <none>                    (no description available)
un  python-parted                             <none>                    <none>                    (no description available)
ii  python-pexpect                            4.0.1-1                   all                       Python module for automating interactive applications
un  python-pexpect-doc                        <none>                    <none>                    (no description available)
ii  python-pil:armhf                          3.1.2-0ubuntu1.3          armhf                     Python Imaging Library (Pillow fork)
un  python-pil-dbg                            <none>                    <none>                    (no description available)
un  python-pil-doc                            <none>                    <none>                    (no description available)
un  python-pil.imagetk                        <none>                    <none>                    (no description available)
un  python-pillow                             <none>                    <none>                    (no description available)
ii  python-pip                                8.1.1-2ubuntu0.4          all                       alternative Python package installer
ii  python-pip-whl                            8.1.1-2ubuntu0.4          all                       alternative Python package installer
un  python-pkg-resources                      <none>                    <none>                    (no description available)
un  python-profiler                           <none>                    <none>                    (no description available)
ii  python-ptyprocess                         0.5-1                     all                       Run a subprocess in a pseudo terminal from Python 2
un  python-pybabel                            <none>                    <none>                    (no description available)
ii  python-pycurl                             7.43.0-1ubuntu1           armhf                     Python bindings to libcurl
un  python-pycurl-dbg                         <none>                    <none>                    (no description available)
un  python-pycurl-doc                         <none>                    <none>                    (no description available)
ii  python-pyexiv2                            0.3.2-5ubuntu4build2      armhf                     Python binding to Exiv2
un  python-pyexiv2-doc                        <none>                    <none>                    (no description available)
un  python-pygments                           <none>                    <none>                    (no description available)
un  python-pylons                             <none>                    <none>                    (no description available)
un  python-pymysql                            <none>                    <none>                    (no description available)
un  python-reportlab-doc                      <none>                    <none>                    (no description available)
un  python-requests-whl                       <none>                    <none>                    (no description available)
ii  python-samba                              2:4.3.11+dfsg-0ubuntu0.16 armhf                     Python bindings for Samba
un  python-scipy-doc                          <none>                    <none>                    (no description available)
un  python-setuptools                         <none>                    <none>                    (no description available)
un  python-setuptools-whl                     <none>                    <none>                    (no description available)
ii  python-simplegeneric                      0.8.1-1                   all                       simple generic functions for Python
un  python-six-whl                            <none>                    <none>                    (no description available)
un  python-smbus                              <none>                    <none>                    (no description available)
un  python-software-properties                <none>                    <none>                    (no description available)
un  python-speechd                            <none>                    <none>                    (no description available)
un  python-support                            <none>                    <none>                    (no description available)
ii  python-talloc                             2.1.5-2                   armhf                     hierarchical pool based memory allocator - Python bindings
ii  python-tdb                                1.3.8-2                   armhf                     Python bindings for TDB
un  python-tk                                 <none>                    <none>                    (no description available)
ii  python-tornado                            4.2.1-1ubuntu3            armhf                     scalable, non-blocking web server and tools
un  python-tz                                 <none>                    <none>                    (no description available)
un  python-uno                                <none>                    <none>                    (no description available)
un  python-urllib3                            <none>                    <none>                    (no description available)
un  python-urllib3-whl                        <none>                    <none>                    (no description available)
un  python-virtualenv                         <none>                    <none>                    (no description available)
un  python-wheel                              <none>                    <none>                    (no description available)
un  python-wsgiref                            <none>                    <none>                    (no description available)
ii  python-wxgtk3.0                           3.0.2.0+dfsg-1build1      armhf                     Python interface to the wxWidgets Cross-platform C++ GUI toolkit
ii  python-wxversion                          3.0.2.0+dfsg-1build1      all                       API for selecting the wxPython version to use
ii  python-zmq                                15.2.0-0ubuntu4           armhf                     Python bindings for 0MQ library
un  python2.5-minimal                         <none>                    <none>                    (no description available)
un  python2.6-minimal                         <none>                    <none>                    (no description available)
ii  python2.7                                 2.7.12-1ubuntu0~16.04.11  armhf                     Interactive high-level object-oriented language (version 2.7)
un  python2.7-argparse                        <none>                    <none>                    (no description available)
un  python2.7-bittorrent                      <none>                    <none>                    (no description available)
un  python2.7-cairo                           <none>                    <none>                    (no description available)
un  python2.7-celementtree                    <none>                    <none>                    (no description available)
un  python2.7-cjkcodecs                       <none>                    <none>                    (no description available)
un  python2.7-crypto                          <none>                    <none>                    (no description available)
un  python2.7-ctypes                          <none>                    <none>                    (no description available)
un  python2.7-doc                             <none>                    <none>                    (no description available)
un  python2.7-elementtree                     <none>                    <none>                    (no description available)
un  python2.7-gobject                         <none>                    <none>                    (no description available)
un  python2.7-gobject-2                       <none>                    <none>                    (no description available)
un  python2.7-ldb                             <none>                    <none>                    (no description available)
un  python2.7-markupsafe                      <none>                    <none>                    (no description available)
ii  python2.7-minimal                         2.7.12-1ubuntu0~16.04.11  armhf                     Minimal subset of the Python language (version 2.7)
un  python2.7-pil                             <none>                    <none>                    (no description available)
un  python2.7-profiler                        <none>                    <none>                    (no description available)
un  python2.7-pyexiv2                         <none>                    <none>                    (no description available)
un  python2.7-samba                           <none>                    <none>                    (no description available)
un  python2.7-talloc                          <none>                    <none>                    (no description available)
un  python2.7-tdb                             <none>                    <none>                    (no description available)
un  python2.7-wsgiref                         <none>                    <none>                    (no description available)
un  python2.7-wxgtk3.0                        <none>                    <none>                    (no description available)
ii  python3                                   3.5.1-3                   armhf                     interactive high-level object-oriented language (default python3 version)
un  python3-all                               <none>                    <none>                    (no description available)
un  python3-all-dbg                           <none>                    <none>                    (no description available)
un  python3-all-dev                           <none>                    <none>                    (no description available)
ii  python3-apt                               1.1.0~beta1ubuntu0.16.04. armhf                     Python 3 interface to libapt-pkg
un  python3-apt-dbg                           <none>                    <none>                    (no description available)
ii  python3-aptdaemon                         1.1.1+bzr982-0ubuntu14.2  all                       Python 3 module for the server and client of aptdaemon
ii  python3-aptdaemon.gtk3widgets             1.1.1+bzr982-0ubuntu14.2  all                       Python 3 GTK+ 3 widgets to run an aptdaemon client
un  python3-aptdaemon.pkcompat                <none>                    <none>                    (no description available)
ii  python3-brlapi                            5.3.1-2ubuntu2.1          armhf                     Braille display access via BRLTTY - Python3 bindings
un  python3-bs4                               <none>                    <none>                    (no description available)
ii  python3-cairo                             1.10.0+dfsg-5build1       armhf                     Python 3 bindings for the Cairo vector graphics library
un  python3-cairocffi                         <none>                    <none>                    (no description available)
ii  python3-chardet                           2.3.0-2                   all                       universal character encoding detector for Python3
ii  python3-commandnotfound                   0.3ubuntu16.04.2          all                       Python 3 bindings for command-not-found.
ii  python3-cups                              1.9.73-0ubuntu2           armhf                     Python3 bindings for CUPS
ii  python3-cupshelpers                       1.5.7+20160212-0ubuntu2   all                       Python modules for printer configuration with CUPS
ii  python3-cycler                            0.9.0-1                   all                       composable kwarg iterator (Python 3)
ii  python3-dateutil                          2.4.2-1                   all                       powerful extensions to the standard datetime module
un  python3-dbg                               <none>                    <none>                    (no description available)
ii  python3-dbus                              1.2.0-3                   armhf                     simple interprocess messaging system (Python 3 interface)
un  python3-dbus-dbg                          <none>                    <none>                    (no description available)
un  python3-dbus.mainloop.qt                  <none>                    <none>                    (no description available)
ii  python3-debian                            0.1.27ubuntu2             all                       Python 3 modules to work with Debian-related data formats
ii  python3-decorator                         4.0.6-1                   all                       simplify usage of Python decorators by programmers
ii  python3-defer                             1.0.6-2build1             all                       Small framework for asynchronous programming (Python 3)
un  python3-dev                               <none>                    <none>                    (no description available)
un  python3-doc                               <none>                    <none>                    (no description available)
un  python3-egenix-mxtexttools                <none>                    <none>                    (no description available)
un  python3-examples                          <none>                    <none>                    (no description available)
un  python3-f2py                              <none>                    <none>                    (no description available)
ii  python3-gdbm:armhf                        3.5.1-1                   armhf                     GNU dbm database support for Python 3.x
un  python3-gdbm-dbg                          <none>                    <none>                    (no description available)
ii  python3-gi                                3.20.0-0ubuntu1           armhf                     Python 3 bindings for gobject-introspection libraries
ii  python3-gi-cairo                          3.20.0-0ubuntu1           armhf                     Python 3 Cairo bindings for the GObject library
un  python3-gobject                           <none>                    <none>                    (no description available)
un  python3-html5lib                          <none>                    <none>                    (no description available)
un  python3-imaging                           <none>                    <none>                    (no description available)
ii  python3-jinja2                            2.8-1ubuntu0.1            all                       small but fast and easy to use stand-alone template engine
ii  python3-louis                             2.6.4-2ubuntu0.4          all                       Python bindings for liblouis
ii  python3-lxml                              3.5.0-1ubuntu0.1          armhf                     pythonic binding for the libxml2 and libxslt libraries
un  python3-lxml-dbg                          <none>                    <none>                    (no description available)
ii  python3-markupsafe                        0.23-2build2              armhf                     HTML/XHTML/XML string library for Python 3
ii  python3-matplotlib                        1.5.1-1ubuntu1            armhf                     Python based plotting system in a style similar to Matlab (Python 3)
ii  python3-minimal                           3.5.1-3                   armhf                     minimal subset of the Python language (default python3 version)
un  python3-ndg-httpsclient                   <none>                    <none>                    (no description available)
un  python3-nose                              <none>                    <none>                    (no description available)
un  python3-notify2                           <none>                    <none>                    (no description available)
ii  python3-numpy                             1:1.11.0-1ubuntu1         armhf                     Fast array facility to the Python 3 language
un  python3-numpy-abi9                        <none>                    <none>                    (no description available)
un  python3-numpy-api10                       <none>                    <none>                    (no description available)
un  python3-numpy-dbg                         <none>                    <none>                    (no description available)
un  python3-numpy-dev                         <none>                    <none>                    (no description available)
un  python3-openssl                           <none>                    <none>                    (no description available)
ii  python3-packagekit                        0.8.17-4ubuntu6~gcc5.4ubu all                       PackageKit backend Python bindings
ii  python3-pexpect                           4.0.1-1                   all                       Python 3 module for automating interactive applications
ii  python3-pil:armhf                         3.1.2-0ubuntu1.3          armhf                     Python Imaging Library (Python3)
un  python3-pil-dbg                           <none>                    <none>                    (no description available)
un  python3-pil.imagetk                       <none>                    <none>                    (no description available)
un  python3-pillow                            <none>                    <none>                    (no description available)
ii  python3-pip                               8.1.1-2ubuntu0.4          all                       alternative Python package installer - Python 3 version of the package
ii  python3-pkg-resources                     20.7.0-1                  all                       Package Discovery and Resource Access using pkg_resources
un  python3-profiler                          <none>                    <none>                    (no description available)
ii  python3-ptyprocess                        0.5-1                     all                       Run a subprocess in a pseudo terminal from Python 3
un  python3-pyasn1                            <none>                    <none>                    (no description available)
ii  python3-pyatspi                           2.18.0+dfsg-3             all                       Assistive Technology Service Provider Interface - Python3 bindings
un  python3-pyatspi2                          <none>                    <none>                    (no description available)
ii  python3-pycurl                            7.43.0-1ubuntu1           armhf                     Python bindings to libcurl (Python 3)
un  python3-pycurl-dbg                        <none>                    <none>                    (no description available)
un  python3-pygments                          <none>                    <none>                    (no description available)
ii  python3-pyparsing                         2.0.3+dfsg1-1ubuntu0.1    all                       Python parsing module, Python3 package
un  python3-pyqt4                             <none>                    <none>                    (no description available)
un  python3-renderpm                          <none>                    <none>                    (no description available)
ii  python3-reportlab                         3.3.0-1ubuntu0.1          all                       ReportLab library to create PDF documents using Python3
ii  python3-reportlab-accel:armhf             3.3.0-1ubuntu0.1          armhf                     C coded extension accelerator for the ReportLab Toolkit
ii  python3-requests                          2.9.1-3ubuntu0.1          all                       elegant and simple HTTP library for Python3, built for human beings
ii  python3-scipy                             0.17.0-1                  armhf                     scientific tools for Python 3
un  python3-setuptools                        <none>                    <none>                    (no description available)
ii  python3-simplegeneric                     0.8.1-1                   all                       simple generic functions for Python3
un  python3-sip                               <none>                    <none>                    (no description available)
ii  python3-six                               1.10.0-3                  all                       Python 2 and 3 compatibility library (Python 3 interface)
un  python3-smbc                              <none>                    <none>                    (no description available)
ii  python3-software-properties               0.96.20.9                 all                       manage the repositories that you install software from
ii  python3-speechd                           0.8.3-1ubuntu3            all                       Python interface to Speech Dispatcher
un  python3-taglib                            <none>                    <none>                    (no description available)
un  python3-tk                                <none>                    <none>                    (no description available)
ii  python3-tornado                           4.2.1-1ubuntu3            armhf                     scalable, non-blocking web server and tools - Python 3 package
ii  python3-tz                                2014.10~dfsg1-0ubuntu2    all                       Python3 version of the Olson timezone database
ii  python3-uno                               1:5.1.6~rc2-0ubuntu1~xeni armhf                     Python-UNO bridge
ii  python3-urllib3                           1.13.1-2ubuntu0.16.04.3   all                       HTTP library with thread-safe connection pooling for Python3
un  python3-venv                              <none>                    <none>                    (no description available)
un  python3-wheel                             <none>                    <none>                    (no description available)
ii  python3-xdg                               0.25-4                    all                       Python 3 library to access freedesktop.org standards
ii  python3-zmq                               15.2.0-0ubuntu4           armhf                     Python3 bindings for 0MQ library
un  python3.0                                 <none>                    <none>                    (no description available)
un  python3.1                                 <none>                    <none>                    (no description available)
un  python3.1-minimal                         <none>                    <none>                    (no description available)
un  python3.3-uno                             <none>                    <none>                    (no description available)
ii  python3.5                                 3.5.2-2ubuntu0~16.04.10   armhf                     Interactive high-level object-oriented language (version 3.5)
un  python3.5-apt                             <none>                    <none>                    (no description available)
un  python3.5-cups                            <none>                    <none>                    (no description available)
un  python3.5-dbus                            <none>                    <none>                    (no description available)
un  python3.5-doc                             <none>                    <none>                    (no description available)
un  python3.5-gdbm                            <none>                    <none>                    (no description available)
un  python3.5-lxml                            <none>                    <none>                    (no description available)
ii  python3.5-minimal                         3.5.2-2ubuntu0~16.04.10   armhf                     Minimal subset of the Python language (version 3.5)
un  python3.5-numpy                           <none>                    <none>                    (no description available)
un  python3.5-reportlab-accel                 <none>                    <none>                    (no description available)
un  python3.5-venv                            <none>                    <none>                    (no description available)
```

**Comment by reddishshoib** [comment]
ERROR: Command errored out with exit status 1:
 command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4_ja8hh2/pandocfilters/setup.py'"'"'; __file__='"'"'/tmp/pip-i                      nstall-4_ja8hh2/pandocfilters/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp                      ile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1v6bwsj7
     cwd: /tmp/pip-install-4_ja8hh2/pandocfilters/
Complete output (3 lines):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'setuptools'
install setuptools using
   pip3 install setuptools
may this can help you
if not then
update your OS
and try again hope this can solve your problem

**Comment by kreston-ru** [comment]
```
:~$ pip3 install setuptools
Defaulting to user installation because normal site-packages is not writeable
Collecting setuptools
  Downloading setuptools-47.1.1-py3-none-any.whl (583 kB)
     |████████████████████████████████| 583 kB 155 kB/s
Installing collected packages: setuptools
Successfully installed setuptools-47.1.1
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

:~$ sudo pip3 install jupyter
[sudo] password for kreston:
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: The directory '/home/kreston/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting ipywidgets
  Downloading ipywidgets-7.5.1-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 124 kB/s

........
........

Collecting attrs>=17.4.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting parso>=0.7.0
  Downloading parso-0.7.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 110 kB/s
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->bleach->nbconvert->jupyter) (2.0.3)
Collecting zipp>=0.5
  Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Could not build wheels for pyzmq, since package 'wheel' is not installed.
Could not build wheels for tornado, since package 'wheel' is not installed.
Could not build wheels for jinja2, since package 'wheel' is not installed.
Could not build wheels for pandocfilters, since package 'wheel' is not installed.
Could not build wheels for decorator, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for backcall, since package 'wheel' is not installed.
Could not build wheels for pexpect, since package 'wheel' is not installed.
Could not build wheels for setuptools, since package 'wheel' is not installed.
Could not build wheels for python-dateutil, since package 'wheel' is not installed.
Could not build wheels for ptyprocess, since package 'wheel' is not installed.
Could not build wheels for pyrsistent, since package 'wheel' is not installed.
Could not build wheels for pyparsing, since package 'wheel' is not installed.
ERROR: jsonschema 3.2.0 has requirement six>=1.11.0, but you'll have six 1.10.0 which is incompatible.
Installing collected packages: ipython-genutils, traitlets, parso, jedi, backcall, pygments, pickleshare, wcwidth, prompt-toolkit, ipython, tornado, jupyter-core, pyzmq, jupyter-client, ipykernel, zipp, importlib-metadata, pyrsistent, attrs, jsonschema, nbformat, Send2Trash, prometheus-client, terminado, mistune, testpath, entrypoints, packaging, webencodings, bleach, pandocfilters, defusedxml, nbconvert, notebook, widgetsnbextension, ipywidgets, jupyter-console, qtpy, qtconsole, jupyter
    Running setup.py install for backcall ... done
  Attempting uninstall: ipython
    Found existing installation: ipython 2.4.1
ERROR: Cannot uninstall 'ipython'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


```
Is it normal?

**Comment by reddishshoib** [comment]
Yes sometimes this error occurs for convenience upgrade pup or pip3

**Comment by nameer** [comment]
This worked for me:

```bash
pip3 install -U setuptools
pip3 install jupyterlab
```

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone for pitching in and happy hacking! :bowtie:
