### ISSUE TITLE
can not start 

### ISSUE THREAD

**Issue by 7568** [jupyter/jupyter#527]
sorry ! https://discourse.jupyter.org/ can not open 

my conda environment is python=3.5 , when I run the command 'conda install -c conda-forge -n testPy35 xarray dask netCDF4 bottleneck',this could success , but I can not run the ' jupyter notebook ', then I remove the "xarray , dask , netCDF4 , bottleneck" , but still can't start the jupyter . 

my conda version is 4.8.3

(testPy35) ➜  python_teaching git:(master) ✗ jupyter notebook
Traceback (most recent call last):
  File "/Users/louis/anaconda3/envs/testPy35/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/notebook/notebookapp.py", line 1602, in initialize
    self.init_webapp()
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/notebook/notebookapp.py", line 1354, in init_webapp
    self.jinja_environment_options,
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/notebook/notebookapp.py", line 275, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/notebook/notebookapp.py", line 1042, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/Users/louis/anaconda3/envs/testPy35/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

**Comment by 7568** [comment]
I restall parso ,solved this problem

**Comment by Aniket99coder** [comment]
> I reinstall 'parso' ,solved this problem

Thanks Man!

**Comment by Krupal09** [comment]
After pip install parso - it says it's already there ! not able to resolve this.
Help is much more appreciated.

**Comment by Krupal09** [comment]
Sorry :D 
It's reinstall :D uninstalled it and installed it again and it works fine :)

**Comment by Sebelandanishvar** [comment]
> I reinstall 'parso' ,solved this problem

Thanks
