### ISSUE TITLE
"Failed to Load Kernel" Error

### ISSUE THREAD

**Issue by felixmaldonadoos** [jupyter/jupyter#542]
I had an issue importing cv2 into python3,9 env A, so i created env gg with python 3.8. Now i got this error when opening a new jupyter notebook in this environment. Im not too familiar with troubleshooting so anything would be appreciated. thank you! felix

Traceback (most recent call last):
File "D:\Anaconda3\envs\gg\lib\site-packages\tornado\web.py", line 1704, in _execute
result = await result
File "D:\Anaconda3\envs\gg\lib\site-packages\tornado\gen.py", line 769, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "D:\Anaconda3\envs\gg\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
model = yield maybe_future(
File "D:\Anaconda3\envs\gg\lib\site-packages\tornado\gen.py", line 762, in run
value = future.result()
File "D:\Anaconda3\envs\gg\lib\site-packages\tornado\gen.py", line 769, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "D:\Anaconda3\envs\gg\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
File "D:\Anaconda3\envs\gg\lib\site-packages\tornado\gen.py", line 762, in run
value = future.result()
File "D:\Anaconda3\envs\gg\lib\site-packages\tornado\gen.py", line 769, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "D:\Anaconda3\envs\gg\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
kernel_id = yield maybe_future(
File "D:\Anaconda3\envs\gg\lib\site-packages\tornado\gen.py", line 762, in run
value = future.result()
File "D:\Anaconda3\envs\gg\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
File "D:\Anaconda3\envs\gg\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
km.start_kernel(**kwargs)
File "D:\Anaconda3\envs\gg\lib\site-packages\jupyter_client\manager.py", line 313, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, **kw)
File "D:\Anaconda3\envs\gg\lib\site-packages\jupyter_client\manager.py", line 222, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "D:\Anaconda3\envs\gg\lib\site-packages\jupyter_client\launcher.py", line 134, in launch_kernel
proc = Popen(cmd, **kwargs)
File "D:\Anaconda3\envs\gg\lib\subprocess.py", line 854, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "D:\Anaconda3\envs\gg\lib\subprocess.py", line 1307, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
