### ISSUE TITLE
Failed to start the ocaml-jupyter kernal in  jupyter notebook  in windows 10

### ISSUE THREAD

**Issue by honey-python-world** [jupyter/jupyter#565]
*******Hey HIi  i have installled ocaml 64  and cygwin64 terminal in windows  10  i   have complete set the kernal  by using this steps https://github.com/akabe/ocaml-jupyter.. but  i  got  kernal error  in top right corner in jupyter notebook , i have used  ocaml kernal version 4.12.0+ mingw64  can  i anyone  please help me to fix this error   THANKS IN ADVANCE *********

Traceback (most recent call last):
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in _async_start_kernel
    self._add_kernel_when_ready(kernel_id, km, ensure_async(km.start_kernel(**kwargs)))
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\manager.py", line 335, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\manager.py", line 257, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 179, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\launcher.py", line 169, in launch_kernel
    raise ex
  File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\launcher.py", line 157, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\honey\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\honey\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by honey-python-world** [comment]
Can any one please help me to solve this issue??? thanks in advance

**Comment by honey-python-world** [comment]
The issue is resolved thanks for your help
