### ISSUE TITLE
ImportError: DLL load failed while importing win32api: 找不到指定的程序。

### ISSUE THREAD

**Issue by kiloGrand** [jupyter/jupyter#567]
Traceback (most recent call last):
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "D:\miniconda3\envs\math_modeling\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "D:\miniconda3\envs\math_modeling\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in _async_start_kernel
    self._add_kernel_when_ready(kernel_id, km, ensure_async(km.start_kernel(**kwargs)))
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "D:\miniconda3\envs\math_modeling\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "D:\miniconda3\envs\math_modeling\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\manager.py", line 331, in _async_start_kernel
    kernel_cmd, kw = await ensure_async(self.pre_start_kernel(**kw))
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\utils.py", line 21, in wrapped
    return loop.run_until_complete(coro(*args, **kwargs))
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "D:\miniconda3\envs\math_modeling\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "D:\miniconda3\envs\math_modeling\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\manager.py", line 298, in _async_pre_start_kernel
    kw = await self.provisioner.pre_launch(**kw)
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 165, in pre_launch
    km.write_connection_file()
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\connect.py", line 516, in write_connection_file
    self.connection_file, cfg = write_connection_file(
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_client\connect.py", line 164, in write_connection_file
    with secure_write(fname) as f:
  File "D:\miniconda3\envs\math_modeling\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "D:\miniconda3\envs\math_modeling\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: 找不到指定的程序。

**Comment by kiloGrand** [comment]
why does this happens?
How to fix it？

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. If you are still having issues, please open a ticket on the `jupyter_client` repository with detailed information about your environment (including versions of the packages involved).

Thanks and happy hacking! :bowtie:
