### ISSUE TITLE
Error in Jupyter installation

### ISSUE THREAD

**Issue by lujonathanh** [jupyter/jupyter#94]
Hello, I currently have Python 2.7.10 on my system. I am running Mac OSX 10.11.1. I successfully installed Anaconda and Jupyter. However, when I run Jupyter, I get the error below. Could someone please help? I'd really like to use Jupyter.

```
Traceback (most recent call last):
  File "/Users/jlu96/anaconda/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/Users/jlu96/anaconda/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/jlu96/anaconda/lib/python3.5/site-packages/notebook/nbextensions.py", line 227, in <module>
    from jupyter_core.application import JupyterApp
  File "/Users/jlu96/anaconda/lib/python3.5/site-packages/jupyter_core/application.py", line 30, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/Users/jlu96/anaconda/lib/python3.5/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/Users/jlu96/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 17, in <module>
    from decorator import decorator
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/decorator.py", line 273, in <module>
    contextmanager = decorator(ContextManager)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/decorator.py", line 234, in decorator
    evaldict = callerfunc.func_globals.copy()
AttributeError: 'function' object has no attribute 'func_globals'
```

**Comment by takluyver** [comment]
It looks like it's running in Python 3.5 but finding a Python 2.7 library somehow. Does `echo $PYTHONPATH` (in a terminal) show you anything? If so, try running `unset PYTHONPATH` before starting Jupyter.

**Comment by lujonathanh** [comment]
This fixed the problem completely! Thank you very much!
